
# Content collections
collections:
  components:
    output: true
    permalink: /docs/:collection/:name/
  services:
    output: false
    permalink: /docs/:collection/:name/
  tutorials:
    output: true
    permalink: /docs/:collection/:name/
  principles:
    output: true
    permalink: /docs/:collection/:name/
  emails:
    output: true
    permalink: /:collection/:name/
  specification-v1:
    output: true
    permalink: /spec/v1/:name/

# Default front-matter
defaults:
  - scope:
      path: ""
    values:
      layout: o-layout-docs
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-post
      author: The Origami Team
  - scope:
      path: ""
      type: emails
    values:
      layout: email-newsletter
      sitemap: false

# Blog post permalinks
permalink: /blog/:year/:month/:day/:title/

# Files and directories to exclude from compilation
exclude:
  - .pa11yci.js
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - node_modules
  - README.md
  - scripts
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

repository: Financial-Times/origami

# Jekyll plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Timezone setting
timezone: Europe/London
